stack: python 3.9

branches:
  only:
    - master

image:
  - Ubuntu2004

build: off

install:
  - ls -a

# Not actually building anything here, but downstream jobs are triggered after this build completes:
# geometrize-lib-docs, geometrize-lib-unit-tests, geometrize-lib-fuzzing, geometrize-lib-example and geometrize
test_script:
  - cd $APPVEYOR_BUILD_FOLDER
  - ls -a

# Note that the documentation generation etc are triggered as a post-build script